backend:
  name: github
  repo: ThibaudLk/simple-gatsby-blog

media_folder: src/images
public_folder: /images

collections:

  # Collection representant les pages du site
  - name: "pages"
    label: "Pages"
    files:
      # La page d'accueil
      # - file: "mdPages/index.md"
      #   label: "Page d'accueil"
      #   name: "index"
      #   fields:
      #     - {label: "Slug", name: "slug", widget: "hidden", default: "index"}
      #     - { label: "Titre", name: "title", widget: "string" }
      #     - { label: "Image", name: "image", widget: image }
      #     - { label: "Heading", name: "heading", widget: "string" }
      #     - { label: "Body", name: "body", widget: "markdown" }
      
      # La page à propos
      - file: "mdPages/about.md"
        label: "À propos"
        name: "about"
        fields:
          - { label: "Slug", name: "slug", widget: "hidden", default: "about"}
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: image }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

          
  # Collection representant les articles du blog
  - name: articles
    label: Articles
    folder: mdArticles
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
